/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class FormUser extends javax.swing.JFrame {
    JobListService jobList = new JobListService();
    MongoDatabase mongoDB = new MongoDatabase();
    /**
     * Creates new form workType1
     */
    public FormUser() {
        initComponents();
        mongoDB.connectDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(810, 850));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel1.setText(">> กฎหมาย");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 65, -1, -1));

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel2.setText(">> เจ้าหน้าที่ขาย-การตลาด/พนักงานขาย-การตลาด");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 92, -1, -1));

        jLabel3.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel3.setText(">> ผู้จัดการ/ผู้ช่วยผู้จัดการขาย-การตลาด");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 124, -1, -1));

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel4.setText(">> ธุรการ/ประสานงาน/คีย์ข้อมูล");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 151, -1, -1));

        jLabel5.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel5.setText(">> ประชาสัมพันธ์/บริการลูกค้า");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 178, -1, -1));

        jLabel6.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel6.setText(">> บุคคล/ฝึกอบรม/Training");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 205, -1, -1));

        jLabel7.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel7.setText(">> นำเข้า/ส่งออก/Shipping/งานด้านต่างประเทศ");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 232, -1, -1));

        jLabel8.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel8.setText(">> ช่างยนต์/ช่างกลโรงงาน/ช่างเทคนิคอุตสาหกรรม");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 259, -1, -1));

        jLabel9.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel9.setText(">> ช่างคอมพิวเตอร์/ช่างเทคนิคคอมพิวเตอร์/Support");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 286, -1, -1));

        jLabel10.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel10.setText(">> ช่างพิมพ์ออฟเซ็ท/อิงค์เจ็ท");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 313, -1, -1));

        jLabel11.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel11.setText(">> โฟร์แมน/ช่างก่อสร้าง/ช่างไม้");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel12.setText(">> ศิลปะ/จิตรกรรม/ออกแบบผลิตภัณฑ์");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 367, -1, -1));

        jLabel13.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel13.setText(">> Web programer/Webmaster");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 394, -1, -1));

        jLabel14.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel14.setText(">> วิศวกรขาย/Sale Engineer");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 421, -1, -1));

        jLabel15.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel15.setText(">> วิศวกรไฟฟ้า/วิศวกรอิเลกทรอนิกส์");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 448, -1, -1));

        jLabel16.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel16.setText(">> วิศวกรสื่อสาร/โทรคมนาคม");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 475, -1, -1));

        jLabel17.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel17.setText(">> วิศวกรเหมืองแร่");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 502, -1, -1));

        jLabel18.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel18.setText(">> สถาปัตยกรรม/ออกแบบตกแต่ง/ประเมินราคา");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 529, -1, -1));

        jLabel19.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel19.setText(">> งานบันเทิง/นักแสดง/พริ๊ตตี้/นักดนตรี/นักร้อง");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 556, -1, -1));

        jLabel20.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel20.setText(">> นักวิทยาศาสตร์การกีฬา/เทรนเนอร์");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 583, -1, -1));

        jLabel21.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel21.setText(">> พัฒนาธุรกิจ/พัฒนาองค์กร ISO");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 610, -1, -1));

        jLabel22.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel22.setText(">> นักข่าว/บรรณาธิการ/นักเขียน/แปลภาษา");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 637, -1, -1));

        jLabel23.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel23.setText(">> งานบริการทั่วไป/บริกร/พนักงานเสิร์ฟ");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 664, -1, -1));

        jLabel24.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel24.setText(">> แพทย์/พยาบาล/เภสัช");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 691, -1, -1));

        jLabel25.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel25.setText(">> วิทยาศาสตร์อาหาร/โภชนาการ");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 718, -1, -1));

        jLabel26.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel26.setText(">> ส่งเอกสาร/ส่งผลิตภัณฑ์/ขับรถ/แม่บ้าน/รปภ.");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 745, -1, -1));

        jLabel27.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel27.setText(">> เร่งรัดหนี้สิน");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 772, -1, -1));

        jLabel28.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel28.setText(">> อื่นๆ");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 799, -1, -1));

        jLabel29.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel29.setText(">> เกษตร/ปศุสัตว์/ประมง/เหมืองแร่");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 65, -1, -1));

        jLabel30.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel30.setText(">> ส่งเสริม/สนับสนุน/ประสานงานการขาย-การตลาด");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 92, -1, -1));

        jLabel31.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel31.setText(">> งานการศึกษา/วิชาการ/อาจารย์");
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 124, -1, -1));

        jLabel32.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel32.setText(">> เลขานุการ");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 151, -1, -1));

        jLabel33.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel33.setText(">> บัญชี/การเงิน-การธนาคาร");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 178, -1, -1));

        jLabel34.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel34.setText(">> จัดซื้อ/คลังสินค้า/logistics");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 205, -1, -1));

        jLabel35.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel35.setText(">> โรงงาน/การผลิต/ควบคุมคุณภาพ");
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 232, -1, -1));

        jLabel36.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel36.setText(">> ช่างไฟฟ้า/ช่างอิเลกทรอนิกส์/ช่างโลหะ");
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 259, -1, -1));

        jLabel37.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel37.setText(">> ช่างจิวเวอร์รี่/ช่างทอง-เงิน");
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 286, -1, -1));

        jLabel38.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel38.setText(">> ดีไซน์เนอร์/ช่างตัดเย็บเสื้อผ้า/ช่างแพทเทิร์น");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 313, -1, -1));

        jLabel39.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel39.setText(">> งานเขียนแบบ/งานDrawing");
        jLabel39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 340, -1, -1));

        jLabel40.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel40.setText(">> Programmer/System Admin/IT");
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 367, -1, -1));

        jLabel41.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel41.setText(">> Web Design/Graphic Design");
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 394, -1, -1));

        jLabel42.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel42.setText(">> วิศวกรเครื่องกล/โรงงาน/วิศวกรอุตสาหกรรม");
        jLabel42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 421, -1, -1));

        jLabel43.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel43.setText(">> วิศวกรโยธา/วิศวกรก่อสร้าง");
        jLabel43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 448, -1, -1));

        jLabel44.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel44.setText(">> วิศวกรคอมพิวเตอร์/วิศวกรระบบ");
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 475, -1, -1));

        jLabel45.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel45.setText(">> วิศวกรสิ่งแวดล้อม");
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 502, -1, -1));

        jLabel46.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel46.setText(">> งานโฆษณา/ขายโฆษณา/Creative/ช่างภาพ");
        jLabel46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 529, -1, -1));

        jLabel47.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel47.setText(">> สุขภาพความงาม/เสริมสวย/สปา/ฟิตเนส");
        jLabel47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 556, -1, -1));

        jLabel48.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel48.setText(">> ผู้จัดการทั่วไป/ผู้อำนวยการ/งานผู้บริหาร");
        jLabel48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 583, -1, -1));

        jLabel49.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel49.setText(">> เศรษฐศาสตร์/สถิติ/งานวิจัย/หุ้น/การประกันภัย");
        jLabel49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 610, -1, -1));

        jLabel50.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel50.setText(">> การโรงแรม/ล่าม/ไกด์/มัคคุเทศก์/งานท่องเที่ยว");
        jLabel50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 637, -1, -1));

        jLabel51.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel51.setText(">> งานด้านอาหาร-เครื่องดื่ม/กุ๊ก/บาร์เทนเดอร์");
        jLabel51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 664, -1, -1));

        jLabel52.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel52.setText(">> วิทยาศาสตร์/เคมี/ชีวะ/สิ่งแวดล้อม/ภูมิศาสตร์");
        jLabel52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel52MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 691, -1, -1));

        jLabel53.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel53.setText(">> เจ้าหน้าที่ความปลอดภัยวิชาชีพ(จป.วิชาชีพ)");
        jLabel53.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel53MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 718, -1, -1));

        jLabel54.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel54.setText(">> งาน Part-time/นักศึกษาฝึกงาน");
        jLabel54.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 745, -1, -1));

        jLabel55.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        jLabel55.setText(">> งานสำหรับผู้พิการ");
        jLabel55.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 772, -1, -1));

        jLabel56.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("ค้นหางานตามประเภท");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 230, 50));

        jLabel57.setBackground(new java.awt.Color(0, 0, 102));
        jLabel57.setOpaque(true);
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setOpaque(true);
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 850));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        jobList.setJobType("อื่นๆ");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        jobList.setJobType("เร่งรัดหนี้สิน");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        jobList.setJobType("ส่งเอกสาร/ส่งผลิตภัณฑ์/ขับรถ/แม่บ้าน/รปภ.");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        jobList.setJobType("วิทยาศาสตร์อาหาร/โภชนาการ");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        jobList.setJobType("แพทย์/พยาบาล/เภสัช");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        jobList.setJobType("งานบริการทั่วไป/บริกร/พนักงานเสิร์ฟ");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        jobList.setJobType("นักข่าว/บรรณาธิการ/นักเขียน/แปลภาษา");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        jobList.setJobType("พัฒนาธุรกิจ/พัฒนาองค์กร ISO");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        jobList.setJobType("นักวิทยาศาสตร์การกีฬา/เทรนเนอร์");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        jobList.setJobType("งานบันเทิง/นักแสดง/พริ๊ตตี้/นักดนตรี/นักร้อง");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        jobList.setJobType("สถาปัตยกรรม/ออกแบบตกแต่ง/ประเมินราคา");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        jobList.setJobType("วิศวกรเหมืองแร่");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        jobList.setJobType("วิศวกรสื่อสาร/โทรคมนาคม");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        jobList.setJobType("วิศวกรไฟฟ้า/วิศวกรอิเลกทรอนิกส์");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        jobList.setJobType("วิศวกรขาย/Sale Engineer");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        jobList.setJobType("Web programer/Webmaster");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        jobList.setJobType("ศิลปะ/จิตรกรรม/ออกแบบผลิตภัณฑ์");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        jobList.setJobType("โฟร์แมน/ช่างก่อสร้าง/ช่างไม้");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        jobList.setJobType("ช่างพิมพ์ออฟเซ็ท/อิงค์เจ็ท");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        jobList.setJobType("ช่างคอมพิวเตอร์/ช่างเทคนิคคอมพิวเตอร์/Support");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        jobList.setJobType("ช่างยนต์/ช่างกลโรงงาน/ช่างเทคนิคอุตสาหกรรม");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        jobList.setJobType("นำเข้า/ส่งออก/Shipping/งานด้านต่างประเทศ");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        jobList.setJobType("บุคคล/ฝึกอบรม/Training");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        jobList.setJobType("ประชาสัมพันธ์/บริการลูกค้า");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jobList.setJobType("ธุรการ/ประสานงาน/คีย์ข้อมูล");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        jobList.setJobType("ผู้จัดการ/ผู้ช่วยผู้จัดการขาย-การตลาด");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        jobList.setJobType("เจ้าหน้าที่ขาย-การตลาด/พนักงานขาย-การตลาด");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        jobList.setJobType("กฎหมาย");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        jobList.setJobType("งานสำหรับผู้พิการ");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel55MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
        jobList.setJobType("งาน Part-time/นักศึกษาฝึกงาน");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel54MouseClicked

    private void jLabel53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseClicked
        jobList.setJobType("เจ้าหน้าที่ความปลอดภัยวิชาชีพ(จป.วิชาชีพ)");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel53MouseClicked

    private void jLabel52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseClicked
        jobList.setJobType("วิทยาศาสตร์/เคมี/ชีวะ/สิ่งแวดล้อม/ภูมิศาสตร์");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel52MouseClicked

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
        jobList.setJobType("งานด้านอาหาร-เครื่องดื่ม/กุ๊ก/บาร์เทนเดอร์");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel51MouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
        jobList.setJobType("การโรงแรม/ล่าม/ไกด์/มัคคุเทศก์/งานท่องเที่ยว");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel50MouseClicked

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        jobList.setJobType("เศรษฐศาสตร์/สถิติ/งานวิจัย/หุ้น/การประกันภัย");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel49MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
        jobList.setJobType("ผู้จัดการทั่วไป/ผู้อำนวยการ/งานผู้บริหาร");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel48MouseClicked

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        jobList.setJobType("สุขภาพความงาม/เสริมสวย/สปา/ฟิตเนส");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        jobList.setJobType("งานโฆษณา/ขายโฆษณา/Creative/ช่างภาพ");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        jobList.setJobType("วิศวกรสิ่งแวดล้อม");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        jobList.setJobType("วิศวกรคอมพิวเตอร์/วิศวกรระบบ");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        jobList.setJobType("วิศวกรโยธา/วิศวกรก่อสร้าง");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        jobList.setJobType("วิศวกรเครื่องกล/โรงงาน/วิศวกรอุตสาหกรรม");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        jobList.setJobType("Web Design/Graphic Design");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        jobList.setJobType("Programmer/System Admin/IT");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        jobList.setJobType("งานเขียนแบบ/งานDrawing");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        jobList.setJobType("ดีไซน์เนอร์/ช่างตัดเย็บเสื้อผ้า/ช่างแพทเทิร์น");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        jobList.setJobType("ช่างจิวเวอร์รี่/ช่างทอง-เงิน");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        jobList.setJobType("ช่างไฟฟ้า/ช่างอิเลกทรอนิกส์/ช่างโลหะ");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        jobList.setJobType("โรงงาน/การผลิต/ควบคุมคุณภาพ");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        jobList.setJobType("จัดซื้อ/คลังสินค้า/logistics");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        jobList.setJobType("บัญชี/การเงิน-การธนาคาร");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        jobList.setJobType("เลขานุการ");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        jobList.setJobType("งานการศึกษา/วิชาการ/อาจารย์");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        jobList.setJobType("ส่งเสริม/สนับสนุน/ประสานงานการขาย-การตลาด");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        jobList.setJobType("เกษตร/ปศุสัตว์/ประมง/เหมืองแร่");
        FormJobList list = new FormJobList();
        list.show();
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        System.out.println("FormUser.main()");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
